import type { Metadata } from "next";
import Link from "next/link";
import { AlertTriangle } from "lucide-react";
import { Logo } from "@/src/components/ui/Logo";

export const metadata: Metadata = {
  title: "Terms of Service | NutriGenius",
  description:
    "NutriGenius Terms of Service — your rights and responsibilities when using our supplement recommendation platform.",
  alternates: {
    canonical: "https://www.nutrigenius.co/terms",
  },
  robots: { index: true, follow: true },
};

const LAST_UPDATED = "18 March 2026";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#f9f9ff]">
      {/* Header */}
      <header className="bg-white shadow-sm shadow-black/5">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <Link href="/" className="hover:opacity-80 transition-opacity duration-200">
            <Logo size="sm" variant="light" />
          </Link>
          <Link
            href="/"
            className="text-sm text-[#5A6578] hover:text-[#00685f] transition-colors"
          >
            ← Back to home
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-10 sm:py-16">
        {/* Title */}
        <div className="mb-8">
          <h1 className="font-heading text-3xl sm:text-4xl font-bold text-[#1A2332] mb-3">
            Terms of Service
          </h1>
          <p className="text-sm text-[#8896A8]">Last updated: {LAST_UPDATED}</p>
          <p className="mt-4 text-[#5A6578] leading-relaxed">
            Please read these Terms of Service carefully before using NutriGenius. By accessing
            or using our service, you agree to be bound by these terms.
          </p>
        </div>

        {/* Prominent Medical Disclaimer */}
        <div className="bg-amber-50 border-2 border-amber-300 rounded-2xl p-6 mb-10 flex gap-4">
          <AlertTriangle className="w-6 h-6 text-amber-600 flex-shrink-0 mt-0.5" />
          <div>
            <h2 className="font-heading text-lg font-bold text-amber-900 mb-2">
              Important Medical Disclaimer
            </h2>
            <p className="text-amber-800 text-sm leading-relaxed">
              <strong>NutriGenius is NOT a medical service.</strong> The supplement recommendations
              provided are for educational and informational purposes only. They do not constitute
              medical advice, diagnosis, or treatment. Always consult a qualified healthcare
              provider before starting any supplement regimen, especially if you have existing
              health conditions or take prescription medications. We are not responsible for any
              health outcomes resulting from use of our recommendations.
            </p>
          </div>
        </div>

        <div className="space-y-10">

          <section id="description">
            <h2 className="font-heading text-xl font-bold text-[#1A2332] mb-3">
              1. Service Description
            </h2>
            <p className="text-[#5A6578] leading-relaxed">
              NutriGenius is a free health information platform that provides personalised
              supplement recommendations based on published scientific evidence. Our service
              includes a health assessment quiz, supplement protocol generation, drug interaction
              screening, evidence ratings, and educational health content. All recommendations
              are generated by an AI system operating on a structured clinical knowledge base.
            </p>
          </section>

          <section id="eligibility">
            <h2 className="font-heading text-xl font-bold text-[#1A2332] mb-3">
              2. Eligibility
            </h2>
            <p className="text-[#5A6578] leading-relaxed">
              You must be at least <strong className="text-[#1A2332]">16 years of age</strong> to
              use NutriGenius. By using our service, you confirm that you meet this requirement.
              If you are under 16, please do not use this service.
            </p>
          </section>

          <section id="responsibilities">
            <h2 className="font-heading text-xl font-bold text-[#1A2332] mb-3">
              3. User Responsibilities
            </h2>
            <ul className="list-disc list-inside text-[#5A6578] space-y-2 ml-2">
              <li>
                Provide accurate and complete information in the health assessment quiz. Inaccurate
                information may result in inappropriate recommendations.
              </li>
              <li>
                Do not rely solely on NutriGenius recommendations for medical decisions. Always
                consult a qualified healthcare professional before acting on our recommendations.
              </li>
              <li>
                Inform your doctor of any supplements you are taking or plan to take.
              </li>
              <li>
                Use the service only for lawful, personal, non-commercial purposes.
              </li>
              <li>
                Do not attempt to reverse engineer, scrape, or commercially exploit our algorithms,
                content, or knowledge base.
              </li>
            </ul>
          </section>

          <section id="medical-disclaimer">
            <h2 className="font-heading text-xl font-bold text-[#1A2332] mb-3">
              4. Medical Disclaimer &amp; Limitations
            </h2>
            <div className="text-[#5A6578] leading-relaxed space-y-3">
              <p>
                NutriGenius provides information based on published peer-reviewed scientific
                evidence. Our recommendations are not prescriptions. Individual health needs vary
                significantly, and what is appropriate for one person may not be appropriate for
                another.
              </p>
              <p>
                Drug interaction screening is informational only and may not capture all possible
                interactions, particularly with rare medications, newly approved drugs, or
                complex polypharmacy situations. A pharmacist or physician should be consulted
                for a comprehensive medication review.
              </p>
              <p>
                In any emergency situation, contact the emergency services in your country
                immediately. Do not use NutriGenius as a substitute for emergency medical care.
              </p>
            </div>
          </section>

          <section id="ai-transparency">
            <h2 className="font-heading text-xl font-bold text-[#1A2332] mb-3">
              5. AI Transparency
            </h2>
            <p className="text-[#5A6578] leading-relaxed">
              Supplement recommendations are generated by an AI system built on a structured
              clinical rules engine and a curated knowledge base of supplement-condition mappings,
              each rated by evidence strength. AI-generated explanations may be produced using
              the Anthropic Claude API. While we strive for accuracy, AI-generated content may
              contain errors or become outdated as new research emerges. We regularly review and
              update our knowledge base.
            </p>
          </section>

          <section id="intellectual-property">
            <h2 className="font-heading text-xl font-bold text-[#1A2332] mb-3">
              6. Intellectual Property
            </h2>
            <p className="text-[#5A6578] leading-relaxed">
              All content, design, algorithms, software, knowledge base, and trademarks on
              NutriGenius are owned by or licensed to NutriGenius and are protected by
              applicable intellectual property laws. You may not reproduce, distribute, or
              create derivative works from our content without prior written permission.
            </p>
          </section>

          <section id="affiliate-disclosure">
            <h2 className="font-heading text-xl font-bold text-[#1A2332] mb-3">
              7. Affiliate Disclosure
            </h2>
            <p className="text-[#5A6578] leading-relaxed">
              As an Amazon Associate, Clareo Health earns from qualifying purchases. When you
              click a product link on our site and make a purchase, we may earn a commission at
              no additional cost to you. This affiliate relationship does not influence our
              supplement recommendations — products are recommended based on scientific evidence,
              not commercial relationships. Prices on third-party sites are set by those
              retailers and may differ from what is shown.
            </p>
          </section>

          <section id="liability">
            <h2 className="font-heading text-xl font-bold text-[#1A2332] mb-3">
              8. Limitation of Liability
            </h2>
            <p className="text-[#5A6578] leading-relaxed mb-3">
              To the fullest extent permitted by applicable law:
            </p>
            <ul className="list-disc list-inside text-[#5A6578] space-y-2 ml-2">
              <li>
                NutriGenius provides the service "as is" and "as available" without warranties
                of any kind, express or implied.
              </li>
              <li>
                We are not liable for any health outcomes, adverse reactions, or harm arising
                from use of or reliance on our recommendations.
              </li>
              <li>
                We are not liable for the quality, safety, or availability of products purchased
                through affiliate links.
              </li>
              <li>
                We are not liable for any interruption, errors, or inaccuracies in the service.
              </li>
              <li>
                Our total liability to you shall not exceed €100 in any circumstances.
              </li>
            </ul>
          </section>

          <section id="termination">
            <h2 className="font-heading text-xl font-bold text-[#1A2332] mb-3">
              9. Termination
            </h2>
            <p className="text-[#5A6578] leading-relaxed">
              We reserve the right to suspend or terminate access to the service at any time,
              for any reason, including if we believe you have violated these Terms. You may
              stop using the service at any time.
            </p>
          </section>

          <section id="governing-law">
            <h2 className="font-heading text-xl font-bold text-[#1A2332] mb-3">
              10. Governing Law &amp; Disputes
            </h2>
            <p className="text-[#5A6578] leading-relaxed">
              These Terms of Service are governed by the laws of Ireland. Any disputes arising
              from or relating to these Terms or your use of NutriGenius shall be subject to
              the exclusive jurisdiction of the courts of Ireland. Nothing in these Terms
              affects your statutory rights as a consumer under Irish or EU consumer protection
              law.
            </p>
          </section>

          <section id="changes">
            <h2 className="font-heading text-xl font-bold text-[#1A2332] mb-3">
              11. Changes to These Terms
            </h2>
            <p className="text-[#5A6578] leading-relaxed">
              We may update these Terms from time to time. The updated version will be posted
              on this page with a new "Last updated" date. Continued use of the service after
              changes constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section id="contact">
            <h2 className="font-heading text-xl font-bold text-[#1A2332] mb-3">
              12. Contact
            </h2>
            <div className="bg-white border border-[#E8ECF1] rounded-xl p-4 text-sm text-[#5A6578] space-y-1">
              <p><strong className="text-[#1A2332]">NutriGenius — Legal</strong></p>
              <p>
                Email:{" "}
                <a href="mailto:legal@nutrigenius.co" className="text-[#00685f] hover:underline">
                  legal@nutrigenius.co
                </a>
              </p>
            </div>
          </section>

        </div>

        {/* Footer nav */}
        <div className="border-t border-[#E8ECF1] pt-8 mt-10 flex flex-wrap gap-4 text-sm text-[#8896A8]">
          <Link href="/privacy" className="hover:text-[#00685f] transition-colors">Privacy Policy</Link>
          <Link href="/disclaimer" className="hover:text-[#00685f] transition-colors">Medical Disclaimer</Link>
          <Link href="/disclosure" className="hover:text-[#00685f] transition-colors">Affiliate Disclosure</Link>
          <Link href="/" className="hover:text-[#00685f] transition-colors ml-auto">← Back to NutriGenius</Link>
        </div>
      </main>
    </div>
  );
}
