import type { Metadata } from "next";
import Link from "next/link";
import { Globe2, ShieldCheck, FlaskConical, Coins, Mail } from "lucide-react";
import { Logo } from "@/src/components/ui/Logo";

export const metadata: Metadata = {
  title: "Affiliate Disclosure | NutriGenius",
  description:
    "NutriGenius Affiliate Disclosure — how we participate in the Amazon Associates program, which regions we route to, and how commissions relate to our evidence-based recommendations.",
  alternates: {
    canonical: "https://www.nutrigenius.co/disclosure",
  },
  robots: { index: true, follow: true },
};

const LAST_UPDATED = "13 April 2026";

const REGIONS = [
  { country: "United States", store: "amazon.com" },
  { country: "United Kingdom / Ireland", store: "amazon.co.uk" },
  { country: "Germany (+ EU)", store: "amazon.de" },
  { country: "France", store: "amazon.fr" },
  { country: "Italy", store: "amazon.it" },
  { country: "Spain", store: "amazon.es" },
  { country: "Turkey", store: "amazon.com.tr" },
];

export default function DisclosurePage() {
  return (
    <div className="min-h-screen bg-[#f9f9ff]">
      {/* Header */}
      <header className="bg-white shadow-sm shadow-black/5">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <Link href="/" className="hover:opacity-80 transition-opacity duration-200">
            <Logo size="sm" variant="light" />
          </Link>
          <Link
            href="/"
            className="text-sm text-[#5A6578] hover:text-[#00685f] transition-colors"
          >
            ← Back to home
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-10 sm:py-16">
        {/* Title */}
        <div className="mb-8">
          <h1 className="font-heading text-3xl sm:text-4xl font-bold text-[#1A2332] mb-3">
            Affiliate Disclosure
          </h1>
          <p className="text-sm text-[#8896A8]">Last updated: {LAST_UPDATED}</p>
        </div>

        {/* Hero */}
        <div className="bg-[#e6f4f3] border-2 border-[#99e8e0] rounded-2xl p-6 mb-10 flex gap-4">
          <ShieldCheck className="w-8 h-8 text-[#00685f] flex-shrink-0 mt-0.5" />
          <div>
            <h2 className="font-heading text-xl font-bold text-[#00685f] mb-2">
              Recommendations are based on evidence, not commissions
            </h2>
            <p className="text-[#005249] leading-relaxed">
              NutriGenius supplement recommendations are generated by a
              clinician-designed algorithm using published clinical trials,
              peer-reviewed research, and established safety standards. Product
              picks are chosen on clinical quality, third-party testing, and
              dosing — never on commission rates.
            </p>
          </div>
        </div>

        <div className="space-y-8">

          {/* Amazon Associates program */}
          <section className="bg-white border border-[#E8ECF1] rounded-2xl p-6">
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-xl bg-[#F0FDFA] flex items-center justify-center flex-shrink-0">
                <Coins className="w-5 h-5 text-[#00685f]" />
              </div>
              <div>
                <h2 className="font-heading text-lg font-bold text-[#1A2332] mb-2">
                  Amazon Associates Program
                </h2>
                <p className="text-[#5A6578] leading-relaxed mb-3">
                  NutriGenius is operated by Clareo Health, a participant in
                  the Amazon Services LLC Associates Program and equivalent
                  affiliate programs in the UK, EU, and Turkey. These are
                  affiliate advertising programs designed to provide a means
                  for sites to earn a small commission by linking to Amazon
                  properties.
                </p>
                <p className="text-[#5A6578] leading-relaxed">
                  When you click a product link on NutriGenius and make a
                  qualifying purchase on Amazon, Clareo Health may earn a
                  commission. <strong>You pay the same price</strong> — the
                  commission is paid by Amazon out of their own margin.
                </p>
              </div>
            </div>
          </section>

          {/* Geo-routed regions */}
          <section className="bg-white border border-[#E8ECF1] rounded-2xl p-6">
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-xl bg-[#F0FDFA] flex items-center justify-center flex-shrink-0">
                <Globe2 className="w-5 h-5 text-[#00685f]" />
              </div>
              <div className="w-full">
                <h2 className="font-heading text-lg font-bold text-[#1A2332] mb-2">
                  Seven Amazon storefronts
                </h2>
                <p className="text-[#5A6578] leading-relaxed mb-4">
                  Affiliate links automatically route to the Amazon storefront
                  nearest to you so you see local pricing, shipping, and
                  availability. Visitors from other EU countries are routed to
                  amazon.de by default.
                </p>
                <div className="grid sm:grid-cols-2 gap-2">
                  {REGIONS.map((r) => (
                    <div
                      key={r.country}
                      className="flex items-center justify-between bg-[#f9f9ff] rounded-lg px-3 py-2 text-sm"
                    >
                      <span className="text-[#1A2332] font-medium">{r.country}</span>
                      <span className="text-[#5A6578] font-mono text-xs">{r.store}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </section>

          {/* How picks are chosen */}
          <section className="bg-white border border-[#E8ECF1] rounded-2xl p-6">
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-xl bg-[#F0FDFA] flex items-center justify-center flex-shrink-0">
                <FlaskConical className="w-5 h-5 text-[#00685f]" />
              </div>
              <div>
                <h2 className="font-heading text-lg font-bold text-[#1A2332] mb-2">
                  How products are chosen
                </h2>
                <p className="text-[#5A6578] leading-relaxed mb-3">
                  Every recommended product is selected on clinical merit:
                </p>
                <ul className="space-y-2 text-[#5A6578] text-sm leading-relaxed">
                  <li className="flex gap-2">
                    <span className="text-[#00685f] mt-1">•</span>
                    <span>
                      <strong>Bioavailable forms</strong> — e.g. magnesium glycinate over magnesium oxide, methylcobalamin over cyanocobalamin, D3 over D2.
                    </span>
                  </li>
                  <li className="flex gap-2">
                    <span className="text-[#00685f] mt-1">•</span>
                    <span>
                      <strong>Third-party testing</strong> — preference for brands with NSF, USP, IFOS, or Informed Sport certification.
                    </span>
                  </li>
                  <li className="flex gap-2">
                    <span className="text-[#00685f] mt-1">•</span>
                    <span>
                      <strong>Clinical dosing</strong> — doses that match the evidence used in the NutriGenius algorithm.
                    </span>
                  </li>
                  <li className="flex gap-2">
                    <span className="text-[#00685f] mt-1">•</span>
                    <span>
                      <strong>Safety</strong> — clean labels, established brands, no undisclosed stimulants or proprietary blends.
                    </span>
                  </li>
                </ul>
                <p className="text-[#5A6578] leading-relaxed mt-4">
                  We show three tiers — <strong>Best Fit</strong>,{" "}
                  <strong>Premium</strong>, and <strong>Budget</strong> — so you
                  can pick the product that matches your preferences and budget.
                  All three meet our clinical bar.
                </p>
              </div>
            </div>
          </section>

          {/* FTC / editorial independence */}
          <section className="bg-white border border-[#E8ECF1] rounded-2xl p-6">
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-xl bg-[#F0FDFA] flex items-center justify-center flex-shrink-0">
                <ShieldCheck className="w-5 h-5 text-[#00685f]" />
              </div>
              <div>
                <h2 className="font-heading text-lg font-bold text-[#1A2332] mb-2">
                  Editorial independence (FTC 16 CFR Part 255)
                </h2>
                <p className="text-[#5A6578] leading-relaxed">
                  In accordance with FTC guidance on endorsements and
                  testimonials, we disclose our affiliate relationships
                  clearly. No brand pays for a placement in the NutriGenius
                  algorithm or in our content. Affiliate commissions never
                  influence which supplements are recommended to you or the
                  order in which tiers appear. If we ever receive free product
                  samples for review, we will say so in the content where they
                  appear.
                </p>
              </div>
            </div>
          </section>

          {/* Questions */}
          <section className="bg-[#111c2c] rounded-2xl p-6">
            <div className="flex items-center gap-3 mb-3">
              <Mail className="w-5 h-5 text-teal-300" />
              <h2 className="font-heading text-lg font-bold text-white">
                Questions about this disclosure?
              </h2>
            </div>
            <p className="text-slate-300 leading-relaxed mb-3">
              If anything on this page is unclear — or if you believe a
              recommended product does not meet the standards above — we want
              to hear about it.
            </p>
            <a
              href="mailto:hello@clareohealth.co"
              className="inline-flex items-center gap-2 text-teal-300 hover:text-teal-200 transition-colors"
            >
              <Mail className="w-4 h-4" />
              hello@clareohealth.co
            </a>
          </section>
        </div>

        {/* Footer nav */}
        <div className="border-t border-[#E8ECF1] pt-8 mt-10 flex flex-wrap gap-4 text-sm text-[#8896A8]">
          <Link href="/methodology" className="hover:text-[#00685f] transition-colors">Methodology</Link>
          <Link href="/disclaimer" className="hover:text-[#00685f] transition-colors">Medical Disclaimer</Link>
          <Link href="/privacy" className="hover:text-[#00685f] transition-colors">Privacy</Link>
          <Link href="/terms" className="hover:text-[#00685f] transition-colors">Terms</Link>
          <Link href="/about" className="hover:text-[#00685f] transition-colors">About</Link>
          <Link href="/" className="hover:text-[#00685f] transition-colors ml-auto">← Back to NutriGenius</Link>
        </div>
      </main>
    </div>
  );
}
