import type { Metadata } from "next";
import Link from "next/link";
import { AlertTriangle, ShieldAlert, Phone, Bot } from "lucide-react";
import { Logo } from "@/src/components/ui/Logo";

export const metadata: Metadata = {
  title: "Medical Disclaimer | NutriGenius",
  description:
    "NutriGenius Medical Disclaimer — important information about the limitations of our supplement recommendations.",
  robots: { index: true, follow: true },
};

const LAST_UPDATED = "18 March 2026";

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-[#f9f9ff]">
      {/* Header */}
      <header className="bg-white shadow-sm shadow-black/5">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <Link href="/" className="hover:opacity-80 transition-opacity duration-200">
            <Logo size="sm" variant="light" />
          </Link>
          <Link
            href="/"
            className="text-sm text-[#5A6578] hover:text-[#00685f] transition-colors"
          >
            ← Back to home
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-10 sm:py-16">
        {/* Title */}
        <div className="mb-8">
          <h1 className="font-heading text-3xl sm:text-4xl font-bold text-[#1A2332] mb-3">
            Medical Disclaimer
          </h1>
          <p className="text-sm text-[#8896A8]">Last updated: {LAST_UPDATED}</p>
        </div>

        {/* Hero warning */}
        <div className="bg-amber-50 border-2 border-amber-300 rounded-2xl p-6 mb-10 flex gap-4">
          <AlertTriangle className="w-8 h-8 text-amber-600 flex-shrink-0 mt-0.5" />
          <div>
            <h2 className="font-heading text-xl font-bold text-amber-900 mb-2">
              NutriGenius is NOT a Medical Service
            </h2>
            <p className="text-amber-800 leading-relaxed">
              The content and supplement recommendations provided by NutriGenius are for{" "}
              <strong>educational and informational purposes only</strong>. Nothing on this
              website constitutes medical advice, diagnosis, or treatment. Always seek the
              advice of a qualified healthcare professional before making any decisions related
              to your health.
            </p>
          </div>
        </div>

        <div className="space-y-8">

          {/* Not a substitute */}
          <div className="bg-white border border-[#E8ECF1] rounded-2xl p-6">
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-xl bg-[#F0FDFA] flex items-center justify-center flex-shrink-0">
                <ShieldAlert className="w-5 h-5 text-[#00685f]" />
              </div>
              <div>
                <h2 className="font-heading text-lg font-bold text-[#1A2332] mb-2">
                  Not a Substitute for Professional Medical Advice
                </h2>
                <p className="text-[#5A6578] leading-relaxed">
                  The personalised supplement recommendations generated by NutriGenius are based
                  on published scientific evidence and a structured clinical knowledge base. They
                  are not prescriptions and are not intended to diagnose, treat, cure, or prevent
                  any disease or medical condition. Individual health needs vary significantly.
                  What is appropriate for one person may be inappropriate or even harmful for
                  another. A qualified healthcare provider — including your general practitioner,
                  specialist, or pharmacist — is best placed to advise you on your individual
                  circumstances.
                </p>
              </div>
            </div>
          </div>

          {/* Drug interactions */}
          <div className="bg-white border border-[#E8ECF1] rounded-2xl p-6">
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-xl bg-[#FEF3C7] flex items-center justify-center flex-shrink-0">
                <AlertTriangle className="w-5 h-5 text-amber-600" />
              </div>
              <div>
                <h2 className="font-heading text-lg font-bold text-[#1A2332] mb-2">
                  Drug Interaction Screening — Informational Only
                </h2>
                <p className="text-[#5A6578] leading-relaxed">
                  NutriGenius screens supplement recommendations against your reported medications
                  to flag potential interactions. However, this screening is{" "}
                  <strong className="text-[#1A2332]">not comprehensive</strong> and may not
                  capture all possible interactions, particularly with:
                </p>
                <ul className="list-disc list-inside text-[#5A6578] space-y-1 mt-3 ml-2">
                  <li>Newly approved or rarely prescribed medications</li>
                  <li>Complex polypharmacy situations (many medications simultaneously)</li>
                  <li>Individual pharmacokinetic variation</li>
                  <li>Over-the-counter medications not listed in the assessment</li>
                </ul>
                <p className="text-[#5A6578] leading-relaxed mt-3">
                  Always consult a pharmacist or physician for a comprehensive medication review
                  before adding any supplement to your regimen.
                </p>
              </div>
            </div>
          </div>

          {/* AI content */}
          <div className="bg-white border border-[#E8ECF1] rounded-2xl p-6">
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-xl bg-[#EEF2FF] flex items-center justify-center flex-shrink-0">
                <Bot className="w-5 h-5 text-indigo-600" />
              </div>
              <div>
                <h2 className="font-heading text-lg font-bold text-[#1A2332] mb-2">
                  AI-Generated Content
                </h2>
                <p className="text-[#5A6578] leading-relaxed">
                  Some content on NutriGenius — including supplement explanations and
                  evidence summaries — may be generated or summarised by AI systems,
                  including the Anthropic Claude API. While we strive for accuracy and
                  regularly review our knowledge base, AI-generated content may contain
                  errors, oversimplifications, or information that has become outdated
                  as new research emerges. We do not guarantee the completeness or
                  accuracy of AI-generated explanations.
                </p>
              </div>
            </div>
          </div>

          {/* Emergency */}
          <div className="bg-red-50 border-2 border-red-200 rounded-2xl p-6">
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-xl bg-red-100 flex items-center justify-center flex-shrink-0">
                <Phone className="w-5 h-5 text-red-600" />
              </div>
              <div>
                <h2 className="font-heading text-lg font-bold text-red-900 mb-2">
                  Emergency Situations
                </h2>
                <p className="text-red-800 leading-relaxed">
                  If you are experiencing a medical emergency — including severe allergic
                  reaction, difficulty breathing, chest pain, or any other life-threatening
                  situation — <strong>contact emergency services immediately</strong> (112 in
                  Ireland and the EU, 999 in the UK, 911 in the US). Do not use NutriGenius
                  as a substitute for emergency medical care.
                </p>
              </div>
            </div>
          </div>

          {/* Consult professional */}
          <div className="bg-white border border-[#E8ECF1] rounded-2xl p-6">
            <h2 className="font-heading text-lg font-bold text-[#1A2332] mb-3">
              Always Consult Your Healthcare Provider
            </h2>
            <p className="text-[#5A6578] leading-relaxed mb-3">
              Before starting any supplement regimen, we strongly recommend that you:
            </p>
            <ul className="list-disc list-inside text-[#5A6578] space-y-2 ml-2">
              <li>Discuss your plans with your general practitioner or relevant specialist</li>
              <li>Consult a pharmacist about potential interactions with your medications</li>
              <li>
                Review current guidelines from reputable health authorities (e.g., HSE Ireland,
                NHS UK, NIH USA)
              </li>
              <li>
                Monitor your response to any new supplement and report any adverse effects to
                your healthcare provider
              </li>
            </ul>
          </div>

          {/* No liability */}
          <div className="bg-[#F8FAFC] border border-[#E8ECF1] rounded-2xl p-6">
            <h2 className="font-heading text-lg font-bold text-[#1A2332] mb-3">
              Limitation of Liability
            </h2>
            <p className="text-[#5A6578] leading-relaxed">
              NutriGenius, its operators, and contributors shall not be held liable for any
              health outcomes, adverse events, or harm arising from your use of or reliance on
              any information or recommendations provided on this platform. Use of this service
              is at your own risk. By using NutriGenius, you acknowledge and accept these
              limitations.
            </p>
          </div>

        </div>

        {/* Footer nav */}
        <div className="border-t border-[#E8ECF1] pt-8 mt-10 flex flex-wrap gap-4 text-sm text-[#8896A8]">
          <Link href="/privacy" className="hover:text-[#00685f] transition-colors">Privacy Policy</Link>
          <Link href="/terms" className="hover:text-[#00685f] transition-colors">Terms of Service</Link>
          <Link href="/" className="hover:text-[#00685f] transition-colors ml-auto">← Back to NutriGenius</Link>
        </div>
      </main>
    </div>
  );
}
